export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const WALLET_READ_REQUEST = 'WALLET_READ_REQUEST';
export const WALLET_READ_SUCCESS = 'WALLET_READ_SUCCESS';
export const WALLET_READ_FAILURE = 'WALLET_READ_FAILURE';

export const WALLET_CREATE_REQUEST = 'WALLET_CREATE_REQUEST';
export const WALLET_CREATE_SUCCESS = 'WALLET_CREATE_SUCCESS';
export const WALLET_CREATE_FAILURE = 'WALLET_CREATE_FAILURE';

export const TRANSACTION_READ_REQUEST = 'TRANSACTION_READ_REQUEST';
export const TRANSACTION_READ_SUCCESS = 'TRANSACTION_READ_SUCCESS';
export const TRANSACTION_READ_FAILURE = 'TRANSACTION_READ_FAILURE';

export const TRANSACTION_CREATE_REQUEST = 'TRANSACTION_CREATE_REQUEST';
export const TRANSACTION_CREATE_SUCCESS = 'TRANSACTION_CREATE_SUCCESS';
export const TRANSACTION_CREATE_FAILURE = 'TRANSACTION_CREATE_FAILURE';

export const SIMULATION_CREATE_REQUEST = 'SIMULATION_CREATE_REQUEST';
export const SIMULATION_CREATE_SUCCESS = 'SIMULATION_CREATE_SUCCESS';
export const SIMULATION_CREATE_FAILURE = 'SIMULATION_CREATE_FAILURE';
