export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const WALLET_READ_REQUEST = 'WALLET_READ_REQUEST';
export const WALLET_READ_SUCCESS = 'WALLET_READ_SUCCESS';
export const WALLET_READ_FAILURE = 'WALLET_READ_FAILURE';

export const WALLET_CREATE_REQUEST = 'WALLET_CREATE_REQUEST';
export const WALLET_CREATE_SUCCESS = 'WALLET_CREATE_SUCCESS';
export const WALLET_CREATE_FAILURE = 'WALLET_CREATE_FAILURE';

export const WALLET_READ_ONE_REQUEST = 'WALLET_READ_ONE_REQUEST';
export const WALLET_READ_ONE_SUCCESS = 'WALLET_READ_ONE_SUCCESS';
export const WALLET_READ_ONE_FAILURE = 'WALLET_READ_ONE_FAILURE';

export const TRANSACTION_READ_REQUEST = 'TRANSACTION_READ_REQUEST';
export const TRANSACTION_READ_SUCCESS = 'TRANSACTION_READ_SUCCESS';
export const TRANSACTION_READ_FAILURE = 'TRANSACTION_READ_FAILURE';

export const TRANSACTION_CREATE_REQUEST = 'TRANSACTION_CREATE_REQUEST';
export const TRANSACTION_CREATE_SUCCESS = 'TRANSACTION_CREATE_SUCCESS';
export const TRANSACTION_CREATE_FAILURE = 'TRANSACTION_CREATE_FAILURE';

export const TRANSACTION_UPDATE_REQUEST = 'TRANSACTION_UPDATE_REQUEST';
export const TRANSACTION_UPDATE_SUCCESS = 'TRANSACTION_UPDATE_SUCCESS';
export const TRANSACTION_UPDATE_FAILURE = 'TRANSACTION_UPDATE_FAILURE';

export const TRANSACTION_DELETE_REQUEST = 'TRANSACTION_DELETE_REQUEST';
export const TRANSACTION_DELETE_SUCCESS = 'TRANSACTION_DELETE_SUCCESS';
export const TRANSACTION_DELETE_FAILURE = 'TRANSACTION_DELETE_FAILURE';
